### ISSUE TITLE
Feature suggestion: allow user to specify tmp folder

### ISSUE THREAD

**Issue by dgoryeo** [gyllila/easy_whisper#1]
As the title says. It would be useful to have a featue that allows user to supply the name/path to the tmp folder --for the cases when the user has used Audacity to create the chunks.

**Comment by gyllila** [comment]
Ok, I‘ll add this feature to the next update, so that the user has the possibility to choose another folder for tmp files.

**Comment by gyllila** [comment]
The update (version 1.1.0) is out there, which no longer uses tmp folder. The processing time is shorter than 1.0.0 thanks to lower-level access to Whisper. NOTE: This is a major update, if you already have version 1.0.0 installed, you'll have to go to the easy_whisper folder in site-packages and delete the two json files for this version to work.
