### ISSUE TITLE
Using in python

### ISSUE THREAD

**Issue by Praj-17** [gyllila/easy_whisper#2]
How to use this package in python code?

**Comment by gyllila** [comment]
Hi Praj, this package is thought to be used stand-alone, but if you prefer to integrate it into another Python script, you can try the following code:

from easy_whisper.trans import transcribe_chunks_m
transcribe_chunks_m(input_dir=DIR, input_file=FILE, language=“en”, task=“transcribe”, model=“tiny.en”)

if you want to transcribe the English audio file FILE in the directory DIR. The transcription will then be saved in DIR next to FILE.

**Comment by Praj-17** [comment]
Thankyou for your insights, I will implement it
