### ISSUE TITLE
Any option to use my fine tuned whisper model 

### ISSUE THREAD

**Issue by asifshaikat** [gyllila/easy_whisper#3]
Hi, Thanks for such easy to use tool. Is there any option so I can use my fine tuned version of whisper by selecting from GUI/or CLI.

**Comment by gyllila** [comment]
Thank you for the nice comment.To your question: if your fine-tuned version has the same structure as a whisper model, say tiny.en, and you are sure you don’t want to use that model, then you can go to the folder storing the Whisper models and replace tiny.en by your own model, then you can use your own model by simply selecting tiny.en.Von meinem iPhone gesendetAm 09.05.2024 um 10:10 schrieb Asif Shaikat ***@***.***>:﻿
Hi, Thanks for such easy to use tool. Is there any option so I can use my fine tuned version of whisper by selecting from GUI/or CLI.
